pub fn ted_disk_patterns() -> &'static [&'static str] {
    &[
        "21-Point Grayscale",
        "10-Point Grayscale",
        "5-Point Grayscale",
        "2-Point Grayscale",
        "Color Bars",
        "Pluge",
        "Sharpness",
        "Overscan",
        "Contrast",
        "Brightness",
        "Near Black",
        "Near White",
        "RGB Steps",
        "RGB Ramp",
        "RGB Ramp Small",
        "Saturation Sweeps",
        "Luminance Sweeps",
        "Color Checker Classic",
        "Color Checker SG",
        "Skin Tones",
        "Memory Colors",
        "Color Space",
        "Gamma",
        "White Balance",
        "HDR Gradient",
        "HDR Peak White",
        "Dolby Vision",
    ]
}
