// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	computeDeltaE: (l1: number, a1: number, b1: number, l2: number, a2: number, b2: number) => __TAURI_INVOKE<number>("compute_delta_e", { l1, a1, b1, l2, a2, b2 }),
	computeXyy: (x: number, y: number, z: number) => __TAURI_INVOKE<[number, number, number]>("compute_xyy", { x, y, z }),
	getAppState: () => __TAURI_INVOKE<AppState>("get_app_state"),
	connectMeter: (meterId: string) => __TAURI_INVOKE<MeterInfo>("connect_meter", { meterId }),
	disconnectMeter: (meterId: string) => __TAURI_INVOKE<null>("disconnect_meter", { meterId }),
	connectDisplay: (displayId: string) => __TAURI_INVOKE<DisplayInfo>("connect_display", { displayId }),
	disconnectDisplay: (displayId: string) => __TAURI_INVOKE<null>("disconnect_display", { displayId }),
	getDeviceInventory: () => __TAURI_INVOKE<DeviceInfo[]>("get_device_inventory"),
	startCalibration: (config: SessionConfigDto) => __TAURI_INVOKE<string>("start_calibration", { config }),
	abortCalibration: (sessionId: string) => __TAURI_INVOKE<null>("abort_calibration", { sessionId }),
	startProfiling: (meterId: string, referenceMeterId: string, displayId: string, config: ProfilingConfig) => __TAURI_INVOKE<string>("start_profiling", { meterId, referenceMeterId, displayId, config }),
	abortProfiling: (sessionId: string) => __TAURI_INVOKE<null>("abort_profiling", { sessionId }),
	getSpectralLocus: (diagram: string) => __TAURI_INVOKE<([number, number])[]>("get_spectral_locus", { diagram }),
	getTargetGamut: (targetSpace: string) => __TAURI_INVOKE<GamutDto>("get_target_gamut", { targetSpace }),
};

/* Types */
export type AppState = {
	meters: MeterInfo[],
	displays: DisplayInfo[],
	calibration_state: CalibrationState,
	last_error: string | null,
};

export type CalibrationState = "Idle" | "Connecting" | "Measuring" | "GeneratingLut" | "Uploading" | "Verifying" | "Error";

export type Chromaticity = {
	x: number,
	y: number,
};

export type DeviceInfo = {
	id: string,
	name: string,
	device_type: string,
	available: boolean,
};

export type DisplayInfo = {
	id: string,
	name: string,
	model: string,
	connected: boolean,
	picture_mode: string | null,
};

export type GamutDto = {
	red: Chromaticity,
	green: Chromaticity,
	blue: Chromaticity,
	white: Chromaticity,
};

export type MeterInfo = {
	id: string,
	name: string,
	serial: string | null,
	connected: boolean,
	capabilities: string[],
};

export type ProfilingConfig = {
	patch_set: string,
	patch_scale: string,
};

export type SessionConfigDto = {
	name: string,
	target_space: string,
	tone_curve: string,
	white_point: string,
	patch_count: number,
	reads_per_patch: number,
	settle_time_ms: number,
	stability_threshold: number | null,
};



// ─── Named command exports (backwards compatibility) ───────────────────────

export const {
	computeDeltaE,
	computeXyy,
	getAppState,
	connectMeter,
	disconnectMeter,
	connectDisplay,
	disconnectDisplay,
	getDeviceInventory,
	startCalibration,
	abortCalibration,
	startProfiling,
	abortProfiling,
	getSpectralLocus,
	getTargetGamut,
} = commands;

// ─── Event constants (manually maintained) ─────────────────────────────────

export const EVENT_DEVICE_STATUS_CHANGED = "device-status-changed" as const;
export const EVENT_CALIBRATION_STATE_CHANGED = "calibration-state-changed" as const;
export const EVENT_ERROR_OCCURRED = "error-occurred" as const;
export const EVENT_CALIBRATION_PROGRESS = "calibration-progress" as const;
export const EVENT_ANALYSIS_COMPLETE = "analysis-complete" as const;
export const EVENT_LUT_UPLOADED = "lut-uploaded" as const;
export const EVENT_VERIFICATION_COMPLETE = "verification-complete" as const;
export const EVENT_PROFILING_PROGRESS = "profiling-progress" as const;
export const EVENT_PROFILING_COMPLETE = "profiling-complete" as const;

export type EventName =
	| typeof EVENT_DEVICE_STATUS_CHANGED
	| typeof EVENT_CALIBRATION_STATE_CHANGED
	| typeof EVENT_ERROR_OCCURRED
	| typeof EVENT_CALIBRATION_PROGRESS
	| typeof EVENT_ANALYSIS_COMPLETE
	| typeof EVENT_LUT_UPLOADED
	| typeof EVENT_VERIFICATION_COMPLETE
	| typeof EVENT_PROFILING_PROGRESS
	| typeof EVENT_PROFILING_COMPLETE;
