// Auto-generated by tauri-specta. Do not edit manually.
// Regenerate with: cargo test export_typescript_bindings --manifest-path src-tauri/Cargo.toml

import { invoke } from "@tauri-apps/api/core";

// ─── Types ───────────────────────────────────────────────────────────────────

export type MeterInfo = {
  id: string;
  name: string;
  serial: string | null;
  connected: boolean;
  capabilities: string[];
};

export type DisplayInfo = {
  id: string;
  name: string;
  model: string;
  connected: boolean;
  picture_mode: string | null;
};

export type CalibrationState =
  | "Idle"
  | "Connecting"
  | "Measuring"
  | "GeneratingLut"
  | "Uploading"
  | "Verifying"
  | "Error";

export type AppState = {
  meters: MeterInfo[];
  displays: DisplayInfo[];
  calibration_state: CalibrationState;
  last_error: string | null;
};

export type DeviceInfo = {
  id: string;
  name: string;
  device_type: string;
  available: boolean;
};

export type DeviceStatusEvent = {
  device_id: string;
  device_type: string;
  connected: boolean;
  info: string;
};

export type CalibrationStateEvent = {
  old_state: CalibrationState;
  new_state: CalibrationState;
  message: string;
};

export type ErrorEvent = {
  severity: string;
  message: string;
  source: string;
};

// ─── Commands ────────────────────────────────────────────────────────────────

export function getAppState(): Promise<AppState> {
  return invoke("get_app_state");
}

export function connectMeter(meterId: string): Promise<MeterInfo> {
  return invoke("connect_meter", { meterId });
}

export function disconnectMeter(meterId: string): Promise<void> {
  return invoke("disconnect_meter", { meterId });
}

export function connectDisplay(displayId: string): Promise<DisplayInfo> {
  return invoke("connect_display", { displayId });
}

export function disconnectDisplay(displayId: string): Promise<void> {
  return invoke("disconnect_display", { displayId });
}

export function getDeviceInventory(): Promise<DeviceInfo[]> {
  return invoke("get_device_inventory");
}

export function computeDeltaE(
  l1: number,
  a1: number,
  b1: number,
  l2: number,
  a2: number,
  b2: number
): Promise<number> {
  return invoke("compute_delta_e", { l1, a1, b1, l2, a2, b2 });
}

export function computeXyy(
  x: number,
  y: number,
  z: number
): Promise<[number, number, number]> {
  return invoke("compute_xyy", { x, y, z });
}

// ─── Event names ─────────────────────────────────────────────────────────────

export const EVENT_DEVICE_STATUS_CHANGED = "device-status-changed" as const;
export const EVENT_CALIBRATION_STATE_CHANGED = "calibration-state-changed" as const;
export const EVENT_ERROR_OCCURRED = "error-occurred" as const;

export type EventName =
  | typeof EVENT_DEVICE_STATUS_CHANGED
  | typeof EVENT_CALIBRATION_STATE_CHANGED
  | typeof EVENT_ERROR_OCCURRED;
