// Auto-generated by tauri-specta. Do not edit manually.
// Regenerate with: cargo test export_typescript_bindings --manifest-path src-tauri/Cargo.toml

import { invoke } from "@tauri-apps/api/core";

// ─── Types ───────────────────────────────────────────────────────────────────

export type MeterInfo = {
  id: string;
  name: string;
  serial: string | null;
  connected: boolean;
  capabilities: string[];
};

export type DisplayInfo = {
  id: string;
  name: string;
  model: string;
  connected: boolean;
  picture_mode: string | null;
};

export type CalibrationState =
  | "Idle"
  | "Connecting"
  | "Measuring"
  | "GeneratingLut"
  | "Uploading"
  | "Verifying"
  | "Error";

export type AppState = {
  meters: MeterInfo[];
  displays: DisplayInfo[];
  calibration_state: CalibrationState;
  last_error: string | null;
};

export type DeviceInfo = {
  id: string;
  name: string;
  device_type: string;
  available: boolean;
};

export type DeviceStatusEvent = {
  device_id: string;
  device_type: string;
  connected: boolean;
  info: string;
};

export type CalibrationStateEvent = {
  old_state: CalibrationState;
  new_state: CalibrationState;
  message: string;
};

export type ErrorEvent = {
  severity: string;
  message: string;
  source: string;
};

export type SessionConfigDto = {
  name: string;
  target_space: string;
  tone_curve: string;
  white_point: string;
  patch_count: number;
  reads_per_patch: number;
  settle_time_ms: number;
  stability_threshold: number | null;
};

export type CalibrationProgress = {
  session_id: string;
  current_patch: number;
  total_patches: number;
  patch_name: string;
  yxy: [number, number, number] | null;
  stable: boolean;
};

export type ProfilingConfig = {
  patch_set: string;
  patch_scale: string;
};

export type ProfilingProgress = {
  session_id: string;
  current_patch: number;
  total_patches: number;
  patch_name: string;
  reference_xyz: [number, number, number];
  meter_xyz: [number, number, number];
  delta_e: number;
};

// ─── Commands ────────────────────────────────────────────────────────────────

export function getAppState(): Promise<AppState> {
  return invoke("get_app_state");
}

export function connectMeter(meterId: string): Promise<MeterInfo> {
  return invoke("connect_meter", { meterId });
}

export function disconnectMeter(meterId: string): Promise<void> {
  return invoke("disconnect_meter", { meterId });
}

export function connectDisplay(displayId: string): Promise<DisplayInfo> {
  return invoke("connect_display", { displayId });
}

export function disconnectDisplay(displayId: string): Promise<void> {
  return invoke("disconnect_display", { displayId });
}

export function getDeviceInventory(): Promise<DeviceInfo[]> {
  return invoke("get_device_inventory");
}

export function computeDeltaE(
  l1: number,
  a1: number,
  b1: number,
  l2: number,
  a2: number,
  b2: number
): Promise<number> {
  return invoke("compute_delta_e", { l1, a1, b1, l2, a2, b2 });
}

export function computeXyy(
  x: number,
  y: number,
  z: number
): Promise<[number, number, number]> {
  return invoke("compute_xyy", { x, y, z });
}

export function startCalibration(config: SessionConfigDto): Promise<string> {
  return invoke("start_calibration", { config });
}

export function abortCalibration(sessionId: string): Promise<void> {
  return invoke("abort_calibration", { sessionId });
}

export function startProfiling(
  meterId: string,
  referenceMeterId: string,
  displayId: string,
  config: ProfilingConfig
): Promise<string> {
  return invoke("start_profiling", { meterId, referenceMeterId, displayId, config });
}

export function abortProfiling(sessionId: string): Promise<void> {
  return invoke("abort_profiling", { sessionId });
}

// ─── Event names ─────────────────────────────────────────────────────────────

export const EVENT_DEVICE_STATUS_CHANGED = "device-status-changed" as const;
export const EVENT_CALIBRATION_STATE_CHANGED = "calibration-state-changed" as const;
export const EVENT_ERROR_OCCURRED = "error-occurred" as const;
export const EVENT_CALIBRATION_PROGRESS = "calibration-progress" as const;
export const EVENT_ANALYSIS_COMPLETE = "analysis-complete" as const;
export const EVENT_LUT_UPLOADED = "lut-uploaded" as const;
export const EVENT_VERIFICATION_COMPLETE = "verification-complete" as const;
export const EVENT_PROFILING_PROGRESS = "profiling-progress" as const;
export const EVENT_PROFILING_COMPLETE = "profiling-complete" as const;

export type EventName =
  | typeof EVENT_DEVICE_STATUS_CHANGED
  | typeof EVENT_CALIBRATION_STATE_CHANGED
  | typeof EVENT_ERROR_OCCURRED
  | typeof EVENT_CALIBRATION_PROGRESS
  | typeof EVENT_ANALYSIS_COMPLETE
  | typeof EVENT_LUT_UPLOADED
  | typeof EVENT_VERIFICATION_COMPLETE
  | typeof EVENT_PROFILING_PROGRESS
  | typeof EVENT_PROFILING_COMPLETE;
